package:
  name: conda-ecosystem-user-package-isolation
  version: 1.0

build:
  number: 1

test:
  commands:
    - test "$PYTHONNOUSERSITE" == "1"         # [unix]
    - test "$R_LIBS_USER" == "-"              # [unix]
    - if not defined PYTHONNOUSERSITE exit 1  # [win]
    - if %PYTHONNOUSERSITE% NEQ 1 exit 1      # [win]

about:
  home: http://conda-forge.org/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: 'Prevent Python and R from searching for packages outside of the current environment'

extra:
  recipe-maintainers:
    - fgp
    - mfansler
