# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "3UbYxnm5paRO8XwCc+AWI11XeFw8Y3bpre7UtfUH7yM5mqCSPb/7Otu+9u5tT6NrWAMGDphzU5LcyIVBajiiECJEWvEd0U1uFgOKwRmmK6I3Bg/9RnLyejX6J/fIXKwKiU34UFAJoDDNqwTvNCqJvrl1tn2RdoBr9mLrwLxQeZQZ5k34zgSZslxz0nz12VzFCTsvEYJcI4TRiYTHKhYI4U+5DewXXZTJNyFjYTDmkGIb7/v4NEgcWspm22FVNWuqhMsW3XBWAgt6qkHucLyWigov/R3L/zApYUJn/lNn2Jh3LS2VG9Wxil17j5JMl5RAGa9z4BPS2lFE2WxyrfMwQtQ92J7nAMEHCb7/E2yMgZljv3fc1ieC7vKbSoFeryQB8hbCJ4u5WKohtBizK9yeSmRiV/oRxKB4uV05XKATSejC1vBeho83XHZqvoZ/8WvyKYU4fzAQLDo4k6UrNxGDuzyCUFdNvuprQKRivvQJst5KksgLORhK5zsE8cxXcxLBvJ947Xro6+VXN1LntRHDKoeKVlqkwD51YECZNIqACB2P3vwjtlbq2qBJfsRfGoia6ZgDSe1uKLdpgWYT4Etwhn9sCJBZmtDqtfXrVIWEJCIGZzHk/wD21d4wCtLwOJ/WG9uiD2xjvk5qgo+9Ixgs6r6SjoZTopnTntBdjjm2mMU="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml