travis:
  secure:
    BINSTAR_TOKEN: 3UbYxnm5paRO8XwCc+AWI11XeFw8Y3bpre7UtfUH7yM5mqCSPb/7Otu+9u5tT6NrWAMGDphzU5LcyIVBajiiECJEWvEd0U1uFgOKwRmmK6I3Bg/9RnLyejX6J/fIXKwKiU34UFAJoDDNqwTvNCqJvrl1tn2RdoBr9mLrwLxQeZQZ5k34zgSZslxz0nz12VzFCTsvEYJcI4TRiYTHKhYI4U+5DewXXZTJNyFjYTDmkGIb7/v4NEgcWspm22FVNWuqhMsW3XBWAgt6qkHucLyWigov/R3L/zApYUJn/lNn2Jh3LS2VG9Wxil17j5JMl5RAGa9z4BPS2lFE2WxyrfMwQtQ92J7nAMEHCb7/E2yMgZljv3fc1ieC7vKbSoFeryQB8hbCJ4u5WKohtBizK9yeSmRiV/oRxKB4uV05XKATSejC1vBeho83XHZqvoZ/8WvyKYU4fzAQLDo4k6UrNxGDuzyCUFdNvuprQKRivvQJst5KksgLORhK5zsE8cxXcxLBvJ947Xro6+VXN1LntRHDKoeKVlqkwD51YECZNIqACB2P3vwjtlbq2qBJfsRfGoia6ZgDSe1uKLdpgWYT4Etwhn9sCJBZmtDqtfXrVIWEJCIGZzHk/wD21d4wCtLwOJ/WG9uiD2xjvk5qgo+9Ixgs6r6SjoZTopnTntBdjjm2mMU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
